// USER PROFILE
export const LOAD_USER_PROFILE = 'LOAD_USER_PROFILE';
export const SET_USER_PROFILE_NAME = 'SET_USER_PROFILE_NAME';
export const SET_USER_PROFILE_EMAIL_ADDRESS = 'SET_USER_PROFILE_EMAIL_ADDRESS';
export const SET_USER_PROFILE_BRANCH = 'SET_USER_PROFILE_BRANCH';

// BRANCH
export const LOAD_BRANCH = 'LOAD_BRANCH';
export const SET_BRANCH_NAME = 'SET_BRANCH_NAME';

// CUSTOMER
export const LOAD_CUSTOMER = 'LOAD_CUSTOMER';
export const SET_CUSTOMER_NAME = 'SET_CUSTOMER_NAME';
export const SET_CUSTOMER_ADDRESS = 'SET_CUSTOMER_ADDRESS';
export const SET_CUSTOMER_EMAIL_ADDRESS = 'SET_CUSTOMER_EMAIL_ADDRESS';
export const SET_CUSTOMER_CURRENCY = 'SET_CUSTOMER_CURRENCY';
export const SET_CUSTOMER_BRANCH = 'SET_CUSTOMER_BRANCH';

// CUSTOMER LIST
export const SET_CUSTOMER_LIST_FILTER = 'SET_CUSTOMER_LIST_FILTER';

// SEARCH
export const APP_SEARCH = 'APP_SEARCH';

// CARGO
export const SET_CARGO_TYPE = 'SET_CARGO_TYPE';
export const TOGGLE_RATED_QUOTE = 'TOGGLE_RATED_QUOTE';
export const ADD_PACKAGE_LINE = 'ADD_PACKAGE_LINE';
export const REMOVE_PACKAGE_LINE = 'REMOVE_PACKAGE_LINE';
export const SET_PACKAGE_LINE_PACKAGE_TYPE = 'SET_PACKAGE_LINE_PACKAGE_TYPE';
export const SET_PACKAGE_LINE_NUM_PACKAGES = 'SET_PACKAGE_LINE_NUM_PACKAGES';
export const SET_PACKAGE_LINE_LENGTH = 'SET_PACKAGE_LINE_LENGTH';
export const SET_PACKAGE_LINE_WIDTH = 'SET_PACKAGE_LINE_WIDTH';
export const SET_PACKAGE_LINE_HEIGHT = 'SET_PACKAGE_LINE_HEIGHT';
export const SET_PACKAGE_LINE_UNIT_VOLUME_UOM = 'SET_PACKAGE_LINE_UNIT_VOLUME_UOM';
export const SET_PACKAGE_LINE_WEIGHT = 'SET_PACKAGE_LINE_WEIGHT';
export const SET_PACKAGE_LINE_WEIGHT_UOM = 'SET_PACKAGE_LINE_WEIGHT_UOM';
export const ADD_CONTAINER_LINE = 'ADD_CONTAINER_LINE';
export const REMOVE_CONTAINER_LINE = 'REMOVE_CONTAINER_LINE';
export const SET_CONTAINER_LINE_NUM_CONTAINERS = 'SET_CONTAINER_LINE_NUM_CONTAINERS';
export const SET_CONTAINER_LINE_CONTAINER_TYPE = 'SET_CONTAINER_LINE_CONTAINER_TYPE';
export const TOGGLE_CONTAINER_LINE_TEMPERATURE_CONTROLLED = 'TOGGLE_CONTAINER_LINE_TEMPERATURE_CONTROLLED';
export const SET_DENSITY_RATIO = 'SET_DENSITY_RATIO';
export const TOGGLE_HAZARDOUS = 'TOGGLE_HAZARDOUS';
export const TOGGLE_TEMPERATURE_CONTROLLED = 'TOGGLE_TEMPERATURE_CONTROLLED';


// MOVEMENT
export const SET_MOVEMENT_MODE = 'SET_MOVEMENT_MODE';
export const SET_MOVEMENT_TERMS_OF_SALE = 'SET_MOVEMENT_TERMS_OF_SALE';
export const SET_MOVEMENT_COMMERCIAL_PARTY = 'SET_MOVEMENT_COMMERCIAL_PARTY';
export const SET_CARRIER = 'SET_CARRIER';
export const SET_RECEIPT = 'SET_RECEIPT';
export const SET_DEPARTURE = 'SET_DEPARTURE';
export const SET_ARRIVAL = 'SET_ARRIVAL';
export const SET_DELIVERY = 'SET_DELIVERY';
export const SET_PICKUP_LOCATION_TYPE = 'SET_PICKUP_LOCATION_TYPE';
export const SET_PICKUP_LOCATION_NAME = 'SET_PICKUP_LOCATION_NAME';
export const SET_PICKUP_COUNTRY = 'SET_PICKUP_COUNTRY';
export const SET_PICKUP_LOCATION = 'SET_PICKUP_LOCATION';
export const SET_PICKUP_POSTAL_CODE = 'SET_PICKUP_POSTAL_CODE';
export const SET_PICKUP_PORT_CODE = 'SET_PICKUP_PORT_CODE';
export const SET_DELIVERY_LOCATION_TYPE = 'SET_DELIVERY_LOCATION_TYPE';
export const SET_DELIVERY_LOCATION_NAME = 'SET_DELIVERY_LOCATION_NAME';
export const SET_DELIVERY_COUNTRY = 'SET_DELIVERY_COUNTRY';
export const SET_DELIVERY_LOCATION = 'SET_DELIVERY_LOCATION';
export const SET_DELIVERY_POSTAL_CODE = 'SET_DELIVERY_POSTAL_CODE';
export const SET_DELIVERY_PORT_CODE = 'SET_DELIVERY_PORT_CODE';

// OTHER SERVICES
export const TOGGLE_INSURANCE = 'TOGGLE_INSURANCE';
export const TOGGLE_CUSTOMS_CLEARANCE = 'TOGGLE_CUSTOMS_CLEARANCE';

// CHARGES
export const ADD_CHARGE_LINE = 'ADD_CHARGE_LINE';
export const REMOVE_CHARGE_LINE = 'REMOVE_CHARGE_LINE';
export const SET_CHARGE_LINE_CODE = 'SET_CHARGE_LINE_CODE';
export const SET_CHARGE_LINE_NAME = 'SET_CHARGE_LINE_NAME';
export const SET_CHARGE_LINE_SELECTED_RATE = 'SET_CHARGE_LINE_SELECTED_RATE';
export const SET_CHARGE_LINE_BASIS = 'SET_CHARGE_LINE_BASIS';
export const SET_CHARGE_LINE_UNITS = 'SET_CHARGE_LINE_UNITS';
export const SET_CHARGE_LINE_UNIT_PRICE = 'SET_CHARGE_LINE_UNIT_PRICE';
export const SET_CHARGE_LINE_CURRENCY = 'SET_CHARGE_LINE_UNIT_PRICES_CURRENCY';
export const SET_CHARGE_NOTES = 'SET_CHARGE_NOTES';
export const SET_FX_CONVERSION_RATE = 'SET_FX_CONVERSION_RATE';
export const SET_QUOTE_CURRENCY = 'SET_QUOTE_CURRENCY';

// LOAD QUOTE
export const LOAD_QUOTE = 'LOAD_QUOTE';

// EMAIL
export const LOAD_EMAIL = 'LOAD_EMAIL';
export const SET_EMAIL_IS_OPEN = 'SET_EMAIL_IS_OPEN';
export const SET_EMAIL_TO = 'SET_EMAIL_TO';
export const SET_EMAIL_CC = 'SET_EMAIL_CC';
export const SET_EMAIL_SUBJECT = 'SET_EMAIL_SUBJECT';
export const SET_EMAIL_MESSAGE = 'SET_EMAIL_MESSAGE';

// RATE
export const LOAD_RATE = 'LOAD_RATE';
export const SET_RATE_TYPE = 'SET_RATE_TYPE';
export const SET_RATE_CHARGE_CODE = 'SET_RATE_CHARGE_CODE';
export const SET_RATE_LEVEL = 'SET_RATE_LEVEL';
export const SET_RATE_ROUTE = 'SET_RATE_ROUTE';
export const SET_RATE_CARRIER = 'SET_RATE_CARRIER';
export const SET_RATE_BASIS = 'SET_RATE_BASIS';
export const SET_RATE_UNIT_PRICE = 'SET_RATE_UNIT_PRICE';
export const SET_RATE_CURRENCY = 'SET_RATE_CURRENCY';
export const SET_RATE_MINIMUM_AMOUNT = 'SET_RATE_MINIMUM_AMOUNT';
