// SEARCH
export const APP_SEARCH = 'APP_SEARCH';

// CARGO
export const SET_CARGO_TYPE                               = 'SET_CARGO_TYPE';
export const TOGGLE_RATED_QUOTE                           = 'TOGGLE_RATED_QUOTE';
export const ADD_PACKAGE_LINE                             = 'ADD_PACKAGE_LINE';
export const REMOVE_PACKAGE_LINE                          = 'REMOVE_PACKAGE_LINE';
export const SET_PACKAGE_LINE_PACKAGE_TYPE                = 'SET_PACKAGE_LINE_PACKAGE_TYPE';
export const SET_PACKAGE_LINE_NUM_PACKAGES                = 'SET_PACKAGE_LINE_NUM_PACKAGES';
export const SET_PACKAGE_LINE_LENGTH                      = 'SET_PACKAGE_LINE_LENGTH';
export const SET_PACKAGE_LINE_WIDTH                       = 'SET_PACKAGE_LINE_WIDTH';
export const SET_PACKAGE_LINE_HEIGHT                      = 'SET_PACKAGE_LINE_HEIGHT';
export const SET_PACKAGE_LINE_UNIT_VOLUME_UOM             = 'SET_PACKAGE_LINE_UNIT_VOLUME_UOM';
export const SET_PACKAGE_LINE_WEIGHT                      = 'SET_PACKAGE_LINE_WEIGHT';
export const SET_PACKAGE_LINE_WEIGHT_UOM                  = 'SET_PACKAGE_LINE_WEIGHT_UOM';
export const ADD_CONTAINER_LINE                           = 'ADD_CONTAINER_LINE';
export const REMOVE_CONTAINER_LINE                        = 'REMOVE_CONTAINER_LINE';
export const SET_CONTAINER_LINE_NUM_CONTAINERS            = 'SET_CONTAINER_LINE_NUM_CONTAINERS';
export const SET_CONTAINER_LINE_CONTAINER_TYPE            = 'SET_CONTAINER_LINE_CONTAINER_TYPE';
export const TOGGLE_CONTAINER_LINE_TEMPERATURE_CONTROLLED = 'TOGGLE_CONTAINER_LINE_TEMPERATURE_CONTROLLED';
export const TOGGLE_HAZARDOUS                             = 'TOGGLE_HAZARDOUS';
export const TOGGLE_TEMPERATURE_CONTROLLED                = 'TOGGLE_TEMPERATURE_CONTROLLED';


// MOVEMENT
export const SET_PICKUP_LOCATION_TYPE   = 'SET_PICKUP_LOCATION_NAME';
export const SET_PICKUP_COUNTRY         = 'SET_PICKUP_COUNTRY';
export const SET_PICKUP_LOCATION        = 'SET_PICKUP_LOCATION';
export const SET_PICKUP_POSTAL_CODE     = 'SET_PICKUP_POSTAL_CODE';
export const SET_PICKUP_PORT_CODE       = 'SET_PICKUP_PORT_CODE';
export const SET_DELIVERY_LOCATION_TYPE = 'SET_DELIVERY_LOCATION_NAME';
export const SET_DELIVERY_COUNTRY       = 'SET_DELIVERY_COUNTRY';
export const SET_DELIVERY_LOCATION      = 'SET_DELIVERY_LOCATION';
export const SET_DELIVERY_POSTAL_CODE   = 'SET_DELIVERY_POSTAL_CODE';
export const SET_DELIVERY_PORT_CODE     = 'SET_DELIVERY_PORT_CODE';

// OTHER SERVICES
export const TOGGLE_INSURANCE         = 'TOGGLE_INSURANCE';
export const TOGGLE_CUSTOMS_CLEARANCE = 'TOGGLE_CUSTOMS_CLEARANCE';

// CHARGES
export const ADD_CHARGE_LINE            = 'ADD_CHARGE_LINE';
export const REMOVE_CHARGE_LINE         = 'REMOVE_CHARGE_LINE';
export const SET_CHARGE_LINE_CODE       = 'SET_CHARGE_LINE_CODE';
export const SET_CHARGE_LINE_NAME       = 'SET_CHARGE_LINE_NAME';
export const SET_CHARGE_LINE_RATE       = 'SET_CHARGE_LINE_RATE';
export const SET_CHARGE_LINE_UNITS      = 'SET_CHARGE_LINE_UNITS';
export const SET_CHARGE_LINE_UNIT_PRICE = 'SET_CHARGE_LINE_AMOUNT';
export const SET_CHARGE_NOTES           = 'SET_CHARGE_NOTES';

// LOAD QUOTE
export const LOAD_QUOTE = 'LOAD_QUOTE';

// EMAIL
export const LOAD_EMAIL        = 'LOAD_EMAIL';
export const SET_EMAIL_IS_OPEN = 'SET_EMAIL_IS_OPEN';
export const SET_EMAIL_TO      = 'SET_EMAIL_TO';
export const SET_EMAIL_CC      = 'SET_EMAIL_CC';
export const SET_EMAIL_SUBJECT = 'SET_EMAIL_SUBJECT';
export const SET_EMAIL_MESSAGE = 'SET_EMAIL_MESSAGE';
